# Generated by Django 3.2.12 on 2023-02-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='next_id',
            field=models.IntegerField(default=0),
        ),
    ]
